name: TestDeployReactApp
on:
  push:
    branches:
      - master
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2 # Pull code tu repo ve may ao
      - run: ls -la
      - run: npm install
      - run: npm run build
      - run : mkdir -p $HOME/.ssh
      - run : echo "${{secrets.PRIVATE_KEY}}" > $HOME/.ssh/private_key
      - run : chmod 600 $HOME/.ssh/private_key
      - name: Send file to server
        run: rsync -azhv -e 'ssh -i $HOME/.ssh/private_key -o StrictHostKeyChecking=no' build/*  --rsync-path='sudo rsync' $user@$server:$target
        env:
          user: root
          server: 139.162.21.110
          target: ~/hello-world
