name: TestDeployReactApp
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Pull code tu repo ve may ao
      - run: ls -la
      - run: npm install
      - run: npm run build
  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - run: ls -la
      - run: eval $(ssh-agent -s)
      - run: ssh-add < echo ${{ secrets.PRIVATE_KEY}}
      - name: Send file to server
        run: rsync -azhv -e 'ssh -o StrictHostKeyChecking=no' build/*  --rsync-path='sudo rsync' $user@$server:$target
        env:
          user: root
          server: 139.162.21.110
          target: ~/hello-world
